version: "3"
volumes:
  appvolume:
services:
  bot-api:
    container_name: bot-api
    build: .
    ports:
      - "8080:5000"
    volumes:
      - ../:/var/run/bot/api
    # ports: ["${BEANSTALKD_HOST_PORT}"]
  # sphinxsearch:
  #   container_name: ${APPLICATION}-sphinxsearch-local
  #   build: ${DOCKER_PACKAGE}/sphinxsearch
  #   ports:
  #     - "${SPHINXSEARCH_HOST_PORT}:${SPHINXSEARCH_HOST_PORT}"
  #   volumes:
  #     - ${SPHINXSEARCH_CONFIG}:/etc/sphinx/
  # redis:
  #   container_name: ${APPLICATION}-redis-local
  #   image: redis:alpine
  #   command: redis-server --requirepass ${REDIS_PASSWORD}
  #   ports: ["${REDIS_PORT}"]
  # db:
  #   container_name: ${APPLICATION}-mysql-local
  #   build:
  #     context: ${DOCKER_PACKAGE}/db
  #   ports:
  #     - "${MYSQL_PORT}:3306"
  #   environment:
  #     MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  #     MYSQL_USER: ${MYSQL_USER}
  #     MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  #     MYSQL_DATABASE: ${MYSQL_DATABASE}
  # php-worker:
  #   container_name: ${APPLICATION}-php-worker
  #   build:
  #     context: ${DOCKER_PACKAGE}/php-worker
  #     args:
  #       - APPLICATION=${APPLICATION}
  #   volumes:
  #     - ${APPLICATION_SRC}:/var/www/${APPLICATION}
  #   depends_on:
  #     - db
  #     - redis
  #     - beanstalkd
  #     - sphinxsearch
  #   links:
  #     - db
  #     - redis
  #     - beanstalkd
  #     - sphinxsearch
  # console:
  #   container_name: ${APPLICATION}-console
  #   build:
  #     context: ${DOCKER_PACKAGE}/console
  #     args:
  #       - APPLICATION=${APPLICATION}
  #   volumes:
  #     - ${APPLICATION_SRC}:/var/www/${APPLICATION}
  #     - ${SSHKEY}:/root/.ssh/
  #   links:
  #     - db
  #     - redis
  #     - beanstalkd
  #     - sphinxsearch
  #   depends_on:
  #     - db
  #     - redis
  #     - beanstalkd
  #     - sphinxsearch
  # php-fpm:
  #   container_name: ${APPLICATION}-php-fpm
  #   build:
  #     context: ${DOCKER_PACKAGE}/php-fpm
  #     args:
  #       - APPLICATION=${APPLICATION}
  #   volumes:
  #     - ${APPLICATION_SRC}:/var/www/${APPLICATION}
  #   ports: ["9000"]
  #   links:
  #     - db
  #     - redis
  #     - beanstalkd
  #     - sphinxsearch
  #   depends_on:
  #     - db
  #     - redis
  #     - beanstalkd
  #     - sphinxsearch
  # nginx:
  #   container_name: ${APPLICATION}-nginx-local
  #   build:
  #     context: ${DOCKER_PACKAGE}/nginx
  #     args:
  #       - PHP_UPSTREAM=php-fpm:9000
  #       - WS_UPSTREAM=php-fpm:9000
  #   volumes:
  #     - ${APPLICATION_SRC}:/var/www/${APPLICATION}
  #     - ${NGINX_SITES_PATH}:/etc/nginx/sites-available
  #   ports:
  #     - "${NGINX_HOST_HTTP_PORT}:80"
  #     - "${NGINX_HOST_HTTPS_PORT}:443"
  #   links:
  #     - php-fpm
  #   depends_on:
  #     - php-fpm
